server:
  port: 8082
  servlet:
    context-path: '/esteiradev/'

spring:
  application:
    name: esteiradev-esteira
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/esteiradev-esteira
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
