server:
  port: 8087
  servlet:
    name: esteiradev-usuario

spring:
  application:
    name: esteiradev-usuario
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/esteiradev-usuario
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

esteiradev:
  auth:
    jwtSecret: LWe9ZnUj7XjEOc6bq2QX0rL7zK+qL4YrbnYdElyxlrKZtAqg3uQqKq4DdNV/pRZcMRlcGmTVmX1zGKrppkxI6A==
    jwtExpirationMs: 14400000

api:
  url:
    esteira: 'http://localhost:8082'